### ISSUE TITLE
Choose Communication Channels

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/communication#1]
Since 1Hive is all about community, and the MVP is going to ship soon, it makes sense to start thinking about how to tell people about this so they can get involved. 

I think there's **a lot** of people who want this stuff, but don't know what's available or how to use it. There is so much untapped utility in the Aragon ecosystem because people don’t really have good examples and documentation on how to leverage these tools. Onboarding docs, education, and outreach initiatives (marketing) could go a long way to help people. Too often brilliant dev projects starve in the graveyard of obscurity. I think we should really focus on community engagement as part of our efforts. That's not to say community engagement just to get likes or reposts, but to actually find people who want to use DAOs and help them understand how they can :)  

### We need to decide:
- which channels we want to use to communication with the world 
- who is responsible for those channels
- how we are going to sync getting content from the community to 1 place (this repo?) to share with the broader community via our communication channels

<br>

## Current Channels
We have a bunch of social media account/channels we can leverage too **if** we want
- [Keybase](https://keybase.io/team/1hive)
- [Email] - hello@1hive.org
- [Twitter](https://twitter.com/1HiveOrg)
- [Reddit](https://www.reddit.com/r/HiveCommons/)
- [Medium](https://medium.com/hive-commons)
- [Gitter](https://gitter.im/1Hive)
- Podcast @0xGabi mentioned that a podcast might be a good idea

Note: I'm not saying that we **should** use **all** of these channels, but just documenting that they exist and that they're an option. I'm actually really happy with Keybase rn, but most people aren't on Keybase, so it's worth considering 1 or 2 options to expand into as well.

<br>

## Potential Channels

We can also reach out to newsletters, podcasts, any media creators in the crypto/blockchain/ethereum space to tell them about 1Hive

### Aragon Community Channels
- forum
- reddit
- monthly newsletter
- what other channels does the Aragon community have to tell people about Aragon related things?

### Ethereum Community Channels
- /r/ethereum 
- /r/ethdev (if people want to engage on issues or learn to make their own DAOs) 
- [Week In Ethereum](https://www.weekinethereum.com/) (and other popular newsletters)
- [EthHub](https://ethhub.io/) 
- what other ways does the Ethereum community communicate and coordinate? Twitter?

### FLOSS Community: anyone who really cares about FLOSS 
- [Nadia Eghbal](https://nadiaeghbal.com/) from [lemonaide stand](https://github.com/nayafia/lemonade-stand)
- [FEM Web3 Business Models](https://github.com/FEMBusinessModelsRing/web3_revenue_primitives/)
- [Hacker News](https://news.ycombinator.com) might care
- [GitHub Open Source Guide](https://opensource.guide/) - looks like they're open to listing resources and/or contributions to the guide - could talk about DAOs and tokens as a model
- Who else is interested in research or applications around decentralized communities and preservation of the commons? 

### TBD
- who else would care about the goals/mission of the project and actually want to get involved and contribute?

# TODO

- [ ] decide on initial communication channels
- [ ] update website, blog, and Medium with new communication channels 
- [ ] share "Hello World" post to all channels to tell people about 1Hive

**Comment by lkngtn** [comment]
Communications:
- Email (1hive.org is using gsuite, currently I'm the only user we can add additional users but it is 6$ per user per month), I think we should also consider a mailing list. 
- Twitter ( I have @1hiveorg and twitter feels like an important channel to maintain )
- Reddit ( I have /r/hivecommons but it is pretty much inactive, I think this could be useful to adopt once we start promoting the hive commons license, but suggest posting to /r/aragonproject for our updates)
- Medium ( I am an editor of the 1hive publication on medium, but we now have a blog at https://1hive.org/blog/ I'm not sure what the best practice is in terms of migrating an audience from medium to a self-hosted blog but we could do some research there).
- Gitter: I think we should drop this and direct people towards keybase chat
- Podcast: This could be a good promotional tool in the future, but I think may be a bit early right now.

**Comment by yeqbfgxjiq** [comment]
I agree on all points. 

I don't think we need more than 1 email address right now, but if being an email admin becomes a chore we can add people or just share the same account. I think it makes sense to focus on using a newsletter and social media to drive engagement, and then using Keybase for messaging. I can't imagine someone wanting to email the project vs chatting on Twitter/Keybase/Reddit/etc... 
- is there really any use for a dedicated email address right now?

Regarding the blog, there's pros and cons:
- Medium drives it's own traffic so it could increase exposure. That being said, once on Medium there's a higher likelihood that someone will skim the post and then click on another blog post.
- The website blog does not deliver it's own traffic, but once people are there it's more likely that they'll click through to the website and then maybe want to get involved. 

With that in mind, I recommend using the website blog and sharing that when we promote 1Hive on Reddit, Twitter, etc... in order to drive more engagement to the homepage and thus the project as a whole
